### ISSUE TITLE
build the homepage.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#3]

**Comment by victorchrollo14** [comment]
## Tasks

- [ ] create a responsive header.
- [ ] create mobile navigation bar.
- [ ] create the Hero Section including responsiveness
- [ ] Add the Brands Section.
- [ ] create homepage product cards component.
- [ ] create the reviews section
- [ ] create the Footer

**Comment by Monilprajapati** [comment]
Done with Home page just need to resize the product card for mobile screens like shop page. 
@victorchrollo14

**Comment by victorchrollo14** [comment]
Do you want me to close it now or after you make the change?

**Comment by Monilprajapati** [comment]
Done ! Issue #42  now we can close this
