### ISSUE TITLE
add user registration and authentication using jwt tokens. and also the user context.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#55]
## Tasks 

- [x] Create routes for registration and login.
- [x] Add controller functions for user registration
- [x] add controller function for user login using jwt tokens.
- [x] create a verifyToken middleware to validate jsonwebtoken from client side.
- [x] create a userContext to manage User data on frontend, plus error and succes states to display relevant errors and success messages

**Comment by victorchrollo14** [comment]
Done.
